CREATE TABLE transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,                 -- NULL = "sem categoria"
    amount      NUMERIC(12, 2) NOT NULL,
    type        VARCHAR(10) NOT NULL,   -- guardado aqui para o saldo não depender da categoria
    description VARCHAR(255),
    occurred_on DATE NOT NULL,          -- dia em que o gasto/receita aconteceu
    created_at  TIMESTAMPTZ NOT NULL,   -- momento em que foi registrado no sistema

    -- Ao apagar uma categoria, as transações ficam sem categoria (não são apagadas).
    CONSTRAINT fk_transactions_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_transactions_type CHECK (type IN ('INCOME', 'EXPENSE'))
);

-- O PostgreSQL NÃO cria índice automaticamente em chave estrangeira.
-- Sem ele, apagar uma categoria varreria a tabela inteira atrás das transações dela.
CREATE INDEX idx_transactions_category_id ON transactions (category_id);

-- Quase toda consulta será "transações do mês X".
CREATE INDEX idx_transactions_occurred_on ON transactions (occurred_on);
