CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,  -- sempre em minúsculas
    password_hash VARCHAR(100) NOT NULL,  -- hash BCrypt (60 caracteres), nunca a senha
    name          VARCHAR(100) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,

    CONSTRAINT uk_users_email UNIQUE (email)
);
