-- Cartões de crédito, separados das categorias.
--
-- Categoria responde "com o QUE gastei" (Alimentação, Casa...).
-- Forma de pagamento + cartão respondem "COMO paguei" (Crédito, cartão BB).
-- Antes, o cartão era cadastrado como categoria ("Cartão BB"), e a despesa
-- perdia a informação do tipo de gasto.
CREATE TABLE cards (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name    VARCHAR(50) NOT NULL,
    CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Mesmo nome não repete na conta, sem diferenciar maiúsculas (igual às categorias, V6).
CREATE UNIQUE INDEX uk_cards_user_lower_name ON cards (user_id, LOWER(name));

-- Cartão usado na despesa. Excluir o cartão deixa a despesa sem cartão
-- (SET NULL), como nas categorias: o histórico não se perde.
ALTER TABLE transactions ADD COLUMN card_id BIGINT;
ALTER TABLE transactions ADD CONSTRAINT fk_transactions_card
    FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE SET NULL;

-- Cartão SÓ em compra no crédito.
-- O contrário ("crédito EXIGE cartão") fica no service, e não aqui: as despesas
-- no crédito lançadas antes desta migration não têm cartão, e um CHECK desses
-- faria a migration falhar no banco de produção. Ao editar uma delas, o app
-- pede o cartão.
ALTER TABLE transactions ADD CONSTRAINT ck_transactions_card_only_credit
    CHECK (card_id IS NULL OR payment_method = 'CREDITO');

-- Toda FK sem índice obriga o banco a varrer transactions inteira ao excluir um
-- cartão (para achar as despesas que apontam para ele).
CREATE INDEX idx_transactions_card ON transactions (card_id);
